server:
  port: 8082

spring:
  cloud:
    config:
      enabled: true
  config:
    import: configserver:http://localhost:8081

  redis:
    host: localhost
    port: 6379

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

my:
  value: "test refresh"